### ISSUE TITLE
[Help Wanted, Question] How to disable blur and reduce GPU usage?

### ISSUE THREAD

**Issue by cardinalpepe** [SardineFish/raindrop-fx#11]
Hello, I'm trying to use your raindrop-fx as a wallpaper, however the GPU usage is very high, I assume (perhaps wrongly, not sure) that the blur effect in the code is eating up a huge amount of GPU, and I assume (perhaps wrongly, not sure) this can be entirely avoided by disabling this blur effect completely and just blurring the image in an image editor.

But it seems that disabling the blur is quite the challenge for me, I tried just setting both mistBlurStep and backgroundBlurSteps to 0
but that just causes the wallpaper to become completely black, I have tried looking in the code (index.js) for a solution to this black screen problem, but I could not find anything that worked,

Also, would disabling blur even reduce the GPU usage, or is it something else eating up the GPU? I have never coded in any programming language. I'm losing my sanity. Please save me.

**Comment by SardineFish** [comment]
Have you tried to set `mist: false` in `RenderingOptions`? Turnning this off should completely disable bluring.

**Comment by SardineFish** [comment]
What GPU are you using? On my GTX 1050Ti with 1080x1920 screen on Chrome. The frame cost is lower than 6ms with both CPU + GPU.

**Comment by cardinalpepe** [comment]
> Have you tried to set `mist: false` in `RenderingOptions`? Turnning this off should completely disable bluring.

Disabling mist entirely does reduce the GPU usage slightly, but it doesn't disable the blur effect being applied to the background image, (as I said before I think that disabling the blur effect in the background will reduce GPU usage, but I'm not sure if it will, what do you think?)

> What GPU are you using? On my GTX 1050Ti with 1080x1920 screen on Chrome. The frame cost is lower than 6ms with both CPU + GPU.

I use a 1660Ti, 3840x1080, having it run with mist on uses 43% of my gpu and having mist off uses 37% of my gpu.

**Comment by SardineFish** [comment]
I reviewed my old code, rendering the blury mist actually cost only one drawcall. The blur pass is only done once when background image or size is changed.
I profiled on my workstation with RTX 3080Ti, it cost only 0.3~0.4 ms during every update. Which should be a very low cost compare to a common video game. While the windows task manager reports at 35% GPU usage.
I think the GPU usage reported by task manager is not reliable.

![image](https://user-images.githubusercontent.com/12628979/193384343-8577be86-1980-4a3f-ae9a-16e26efc3e0d.png)

**Comment by SardineFish** [comment]
Do you suffered any system latency or frame drop while running this raindrop page together with a video game?
The most heavy works in this raindrop effect is actually on CPU side, which have to simulate thousands of sliding droplets.

**Comment by cardinalpepe** [comment]
Thank you SardineFish for your response, the only reason I was worrying about the GPU usage is because I view my desktop alot,
the constant use of gpu, and repeatedly cooling down and heating up when I'm not viewing the desktop might be harmful for my GPU, as the wallpaper pauses once a window is maximized (not viewing the desktop).

I have not attempted to play a game while having the wallpaper running, and I think you might be right with taskmanager not being accurate with gpu usage, thank you for helping and responding.

**Comment by SardineFish** [comment]
I think you don't have to wory about using GPU repeatedly cooling down and heating up. Actually the system always use your GPU to do a lot rendering works while you may not notice it. 
For example, when I minimize my chome window, the GPU usage immediately gose to 40% and quickly drop to 10%.
PC hardware is much more durable than you thought.
