### ISSUE TITLE
部分场景四周边缘生成的雨滴泛白比较奇怪

### ISSUE THREAD

**Issue by leon-kfd** [SardineFish/raindrop-fx#12]
如题，这个有办法解决吗？在背景图为浅色的场景容易出现。
![image](https://user-images.githubusercontent.com/30256102/211517975-ce09d090-c850-4018-a6e7-38e0c0c4f200.png)
![image](https://user-images.githubusercontent.com/30256102/211518123-7f863990-f6da-4f76-b948-fea4b772a9d8.png)

**Comment by SardineFish** [comment]
欸，对不起，没仔细审题，雨滴的问题我再确认一下

**Comment by SardineFish** [comment]
确认了一下问题出自 `blurryBackground` texture 的 `wrapMode` 默认为 repeat，在屏幕边缘的雨滴计算偏折采样时越过边界采样到了另一边的画面，在上下边缘颜色明显不一致的时候就会出现这个现象，
![image](https://user-images.githubusercontent.com/12628979/211573983-31a95e81-822a-40e5-bb81-7e92f26ea121.png)
![image](https://user-images.githubusercontent.com/12628979/211574019-9bc7fba6-6e52-4136-bc28-ddf5dca047d1.png)

改为 Clamp 之后：
![image](https://user-images.githubusercontent.com/12628979/211574253-0b54a6b4-5893-4715-8711-dccae4110849.png)
![image](https://user-images.githubusercontent.com/12628979/211574283-7cfc3726-beab-4725-b6d8-e9e182ca72a7.png)

Clamp 会在超出 UV 范围时保留边缘的颜色，但是这样对于画面边缘的折射效果可能并不是很好，我也尝试了一下 Mirror 的模式，效果也差不多，准备做成一个可选项吧。更好的解决方案或许需要对背景做一定的裁切。
