### ISSUE TITLE
canvas销毁后，object does not belong to this context

### ISSUE THREAD

**Issue by Aobanana-chan** [SardineFish/raindrop-fx#7]
非常棒的项目。
我在vue3上使用raindrop-fx，正常情况下，raindrop-fx工作的非常好

但我尝试使用vue router作为前端路由，在路由跳转后跳回来，canvas被销毁然后重建，回来后canvas并不能正常渲染，只有黑白，背景图也没有渲染出来。控制台有很多诸如WebGL: INVALID_OPERATION: bindFramebuffer: object does not belong to this context的错误。

在调试跟踪，发现
```
        if (!GlobalContext())
            this.use();
```
GlobalContext()仍然为之前销毁的canvas的值，use()函数并没有运行，于是我尝试在这个代码运行时候下断，控制台调用了ZograRenderer的use函数，此时背景图成功渲染出来，但是落雨效果并没有渲染。控制台还是有很多WebGL: INVALID_OPERATION: bindFramebuffer: object does not belong to this context这样的类似的错误。

此时控制台输出错误的堆栈大概是，
```
bind  RainDrop.vue_vue_typ…3.js:formatted:7577
drawMeshProceduralInstance  RainDrop.vue_vue_typ…3.js:formatted:8057
drawDroplet   RainDrop.vue_vue_typ…3.js:formatted:9333
render   RainDrop.vue_vue_typ…3.js:formatted:9256
update  RainDrop.vue_vue_typ…3.js:formatted:9642
```

我觉得奇怪的是，如果context是错误的，背景图应该也不会渲染，context是正确的话，为什么落雨不渲染。我对webgl并不是很了解，不明白为什么会这样，请大佬解答。

**Comment by Aobanana-chan** [comment]
好像还有内存泄露的问题，canvas删除时，webgl的context没有释放，update函数始终在执行，就算stop了，context依旧不释放。此时再新建canvas，然后new RaindropFx()，就必定出现这个问题。

**Comment by SardineFish** [comment]
嘶……完全没有管过销毁的问题 Orz，Context 做成全局的也没有考虑过多个实例的冲突问题 Orz。
应该在删除  canvas 之后把 RaindropFX class 里所有引用的 WebGL 资源都 destroy 掉，然后重置一些全局状态应该就能解决？
可能周末才有空看看了

**Comment by SardineFish** [comment]
这里面用的是我自己封装的一个渲染器，里面的资源 Texture，FrameBuffer 之类的都有个 `destroy()` 函数

**Comment by Aobanana-chan** [comment]
emm GLContext和资源销毁逻辑都在ZograRenderer，ZograRenderer也没有写过类似dispose的函数，感觉上得改一下ZograRenderer的结构了，没写过渲染器，不太懂，爱莫能助了 ：3

**Comment by SardineFish** [comment]
看了一下这个项目引用的 `zogra-renderer` 版本，大部分 GL 资源比如 `Texture`，`Shader`，`Material` 都在 AssetManager 里有注册引用，可以直接遍历清理，raindrop 里用了一个 `RenderBuffer` 没有纳入资源管理，需要手动清理一下

**Comment by SardineFish** [comment]
`GlobalContext` 的清理直接调用 `setGlobalContext(null)` 应该就可以了

**Comment by Aobanana-chan** [comment]
了解，有空我试试看。要是行了我交个PR。不过setGlobalContext(null)在Typescript4.8.2会爆红， 得强行改成setGlobalContext(null as any)这种不太优雅的形式 XD

**Comment by Aobanana-chan** [comment]
emm 今天试了下，assetsMap被设置成了private，没有一种简单的方法能拿到assetMap，还是得改渲染器源码，然而我这边Vite打包源码失败了，`Unexpected token (Note that you need plugins to import files that are not JavaScript)`，得需要插件打包shader

**Comment by SardineFish** [comment]
raindrop 引用的 `zogra-renderer` 里面应该没有需要打包的 shader 引用，都是硬编码在 ts 里的。你可能用了 `master` 上的版本？这上面可能做了一些不兼容的重构

**Comment by SardineFish** [comment]
我今晚抽点时间先把 raindrop 改成用 `master` 最新的 `zogra-renderer` 吧，如果你有时间的话可以在 `master` 的基础上做修改

**Comment by SardineFish** [comment]
顺手把资源销毁的问题解决了，可以试试新版
